---
- name: start tmp podcast.xml file
  template:
    src: templates/podcast.xml.j2
    dest: /tmp/{{ podcastxml }}
  when: itunes.category.text != ''

- name: start tmp podcast.xml file
  template:
    src: templates/podcast_sc.xml.j2
    dest: /tmp/{{ podcastxml }}
  when: itunes.category.text == ''

- name: return search results from archive.org
  uri:
    url: '{{ archive.search_url }}?q=creator:({{ archive.creator|replace(" ", "+") }}) AND title:({{ archive.title|replace(" ", "+") }})&output=json&sort[]=date asc'
    method: GET
    status_code: 200
    body_format: json
  register: archive

# grab media locally to extract metadata.  (no id3 tags)
- name: populate podcast items
  include: tasks/getpod.yml
  loop: "{{ archive.json.response.docs }}"

- name: close out our xml file
  lineinfile:
    path: /tmp/{{ podcastxml }}
    line: |
          </channel>
          </rss>

# alright, do a compare on new vs old podcast.xml file.  if there are changes,
# identify number of items, titles, and email them to someone.

- name: tidy xml for publication
  shell: xmllint --format /tmp/{{ podcastxml }} > {{ playbook_dir }}/{{ podcastxml }}

#- name: fix my &
#  shell: sed -i 's/\&amp;/\&/g' {{ playbook_dir }}/{{ podcastxml }}
#  shell: sed -i 's/\ \&\ /\&amp;/g' {{ playbook_dir}}/{{ podcastxml }}

- file:
    state: absent
    path: /tmp/{{ podcastxml }}
