---
- name: start tmp podcast.xml file
  template:
    src: templates/podcast.xml.j2
    dest: /tmp/{{ podcastxml }}

- name: return search results from archive.org
  uri:
    url: '{{ archive.search_url }}?q=creator:({{ archive.creator|replace(" ", "+") }}) AND title:({{ archive.title|replace(" ", "+") }})&output=json&sort[]=date asc'
    method: GET
    status_code: 200
    body_format: json
  register: archive

- name: build some download stats
  set_fact:
    downloads: "{{ downloads | default() }} + 'Description: {{ item.description }} - Downloads: {{ item.downloads }}\n'"
  loop: "{{ archive.json.response.docs }}"

#- debug: msg="{{ downloads }}"
#- meta: end_play

# grab media locally to extract metadata.  (no id3 tags)
- name: populate podcast items
  include: tasks/getpod.yml
  loop: "{{ archive.json.response.docs }}"

- name: close out our xml file
  lineinfile:
    path: /tmp/{{ podcastxml }}
    line: |
          </channel>
          </rss>

# alright, do a compare on new vs old podcast.xml file.  if there are changes,
# identify number of items, titles, and email them to someone.

- name: tidy xml for publication
  shell: xmllint --format /tmp/{{ podcastxml }} > {{ playbook_dir }}/{{ podcastxml }}

- file:
    state: absent
    path: /tmp/{{ podcastxml }}
