---
- name: start tmp podcast.xml file
  template:
    src: templates/podcast.xml.j2
    dest: /tmp/{{ podcastxml }}

- name: return search results from archive.org
  uri:
    url: '{{ archive.search_url }}?q=creator:({{ archive.creator|replace(" ", "+") }})%20AND%20title:({{ archive.title|replace(" ", "+") }})&output=json&sort[]=date%20asc'
    method: GET
    status_code: 200
    body_format: json
  register: archive

- name: build some download stats
  set_fact:
    downloads: "{{ downloads | default() }} + 'Description: {{ item.description }} - Downloads: {{ item.downloads }}\n'"
  loop: "{{ archive.json.response.docs }}"

# grab media locally to extract metadata.  (no id3 tags)
- name: populate podcast items
  include: tasks/getpod.yml
  loop: "{{ archive.json.response.docs }}"

- name: close out our xml file
  lineinfile:
    path: /tmp/{{ podcastxml }}
    line: |
          </channel>
          </rss>

- name: tidy xml for publication
  shell: xmllint --format /tmp/{{ podcastxml }} > /tmp/{{ podcastxml }}.tidy

# alright, do a compare on new vs old podcast.xml file.  if there are changes,
# identify number of items, titles, and email them to someone.

# but first, do we have an old podcast file?
- name: look for previously generated podcast xml 
  stat:
    path: "{{ playbook_dir }}/{{ podcastxml }}"
  register: previouspod

- block:
    - name: do a compare vs old podcast.xml file (if it exists). if there are chanages, inform via email
      shell: diff {{ playbook_dir }}/{{ podcastxml }} /tmp/{{ podcastxml }}.tidy
      register: diff
      ignore_errors: yes

# {{ itunes.owner.email }}"
    - name: email user with the news
      mail:
#        headers:
#        - Reply-To:={{ ena_replyto }}
        charset: us-ascii
#        host: "{{ ena_smtp }}"
#        from: ""
        to: "nilesingalls@gmail.com"
        subject: "podcast information"
        body:  >-
           something changes, perhaps a new podcast! possibly just an edit.  podcast.xml file attached.
        attach:
          - "{{ playbook_dir }}/{{ podcastxml }}"
      when: diff.stdout | length > 0

  when: previouspod.stat.exists == true

- name: tidy xml for publication
  shell: xmllint --format /tmp/{{ podcastxml }} > {{ playbook_dir }}/{{ podcastxml }}

- file:
    state: absent
    path: /tmp/{{ item }}
  loop:
    - "{{ podcastxml }}"
    - "{{ podcastxml }}.tidy"
